import type { Finding } from "../types.js";
import { summarize, sortFindings, riskOf } from "./summary.js";

const STATUS_ICON: Record<string, string> = {
  fail: "❌",
  warn: "⚠️",
  pass: "✅",
  skipped: "⏭️",
  error: "🔧",
};

const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

export function renderMarkdown(
  findings: Finding[],
  meta: { baseUrl: string; realm: string; date: string; mode: string },
): string {
  const s = summarize(findings);
  const sorted = sortFindings(findings);
  const lines: string[] = [];

  lines.push(`# Audit Report — Keycloak Security Audit`);
  lines.push("");
  lines.push(`- **Target**: ${meta.baseUrl}`);
  lines.push(`- **Realm**: ${meta.realm}`);
  lines.push(`- **Mode**: ${meta.mode}`);
  lines.push(`- **Date**: ${meta.date}`);
  lines.push("");
  lines.push(`## Score: ${s.score}/100`);
  lines.push("");
  lines.push(
    `**Risk exposure**: ${s.risk} weighted points (impact × likelihood, score = 100 − risk).`,
  );
  lines.push("");
  lines.push(
    `| Critical | High | Medium | Low | ✅ Pass | ⚠️ Warn | ❌ Fail |`,
  );
  lines.push(`|---|---|---|---|---|---|---|`);
  lines.push(
    `| ${s.bySeverity.critical} | ${s.bySeverity.high} | ${s.bySeverity.medium} | ${s.bySeverity.low} | ${s.byStatus.pass} | ${s.byStatus.warn} | ${s.byStatus.fail} |`,
  );
  lines.push("");

  // Top risks (highest weighted findings)
  const ranked = sorted.filter((f) => riskOf(f).score > 0).slice(0, 5);
  if (ranked.length) {
    lines.push(`## Top risks`);
    lines.push("");
    lines.push(`| # | Risk | Score | Finding | Category |`);
    lines.push(`|---|---|---|---|---|`);
    ranked.forEach((f, i) => {
      const r = riskOf(f);
      lines.push(
        `| ${i + 1} | ${cap(r.level)} | ${r.score} | ${f.title} | ${f.category} |`,
      );
    });
    lines.push("");
  }

  // Group by category
  const byCat = new Map<string, Finding[]>();
  for (const f of sorted) {
    if (!byCat.has(f.category)) byCat.set(f.category, []);
    byCat.get(f.category)!.push(f);
  }

  for (const [cat, items] of byCat) {
    lines.push(`## ${cat}`);
    lines.push("");
    for (const f of items) {
      const icon = STATUS_ICON[f.status] ?? "•";
      const sev = f.status === "pass" || f.status === "skipped" ? "" : ` _(${f.severity})_`;
      lines.push(`### ${icon} ${f.title}${sev}`);
      if (f.resource) lines.push(`- **Resource**: \`${f.resource}\``);
      lines.push(`- ${f.detail}`);
      const r = riskOf(f);
      if (r.score > 0)
        lines.push(
          `- 🎯 **Risk**: ${cap(r.level)} (${r.score}) — impact ${f.severity} × likelihood ${
            f.status === "fail" ? "confirmed" : "potential"
          }`,
        );
      if (f.recommendation && f.status !== "pass")
        lines.push(`- 💡 ${f.recommendation}`);
      if (f.references?.length)
        lines.push(`- 🔗 ${f.references.map((r) => `<${r}>`).join(" ")}`);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(
    `_Generated by Keycloak Security Audit. This audit is non-exhaustive and does not replace a manual penetration test._`,
  );
  return lines.join("\n");
}
